replicaCount: 1

image:
  repository: mohamdevx/go-web-app
  tag: latest
  pullPolicy: IfNotPresent


service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: nginx
  host: go-web-app.local